Properties are place in manifest, not in cloud config
- test_upgrade does not depend on deprecated bosh-init resource

fixes:
```
Error: Unable to render jobs for instance group 'iam-instance-profile-test'. Errors are:
   - Unable to render templates for job 'iam-instance-profile-test'. Errors are:
        - Error filling in template 'run.erb' (line 12: Can't find property '["iam_instance_profile"]')
```

fixes:
```
missing inputs: bosh-init
```

Signed-off-by: Brian Cunnie <bcunnie@pivotal.io>

[#127591451](https://www.pivotaltracker.com/story/show/127591451)